### ISSUE TITLE
UnboundLocalError: cannot access local variable 'FORMAT' where it is not associated with a value

### ISSUE THREAD

**Issue by cpswan** [sbomify/github-action#13]
When running the action with:

```yaml
    - name: Upload SBOM
      uses: sbomify/github-action@master
      env:
        TOKEN: ${{ secrets.SBOMIFY_TOKEN }}
        COMPONENT_ID: 'GZ7pLm8m_a'
        LOCK_FILE: './packages/dart/sshnoports/pubspec.lock'
        SBOM_VERSION: ${{github.ref_name}}
        OUTPUT_FILE: 'tarballs/dart_sshnoports_sbom.cdx.json'
        AUGMENT: true
        ENRICH: true
        UPLOAD: true
```

It fails:

```log
[Info] Using input file './packages/dart/sshnoports/pubspec.lock'.
[Info] Detected Dart lockfile
Traceback (most recent call last):
  File "/usr/src/app/entrypoint.py", line 571, in <module>
    main()
    ~~~~^^
  File "/usr/src/app/entrypoint.py", line 496, in main
    SPEC_VERSION = get_spec_version(FORMAT, sbom_data)
                                    ^^^^^^
UnboundLocalError: cannot access local variable 'FORMAT' where it is not associated with a value
```

Here's the full [action run](https://github.com/cpswan/release_automation/actions/runs/11591943539/job/32272803591)

**Comment by vpetersson** [comment]
Digging around a bit here, and it seems like `FORMAT` is [here](https://github.com/sbomify/github-action/blob/master/entrypoint.py#L376) if you are providing an SBOM. In the above use case, a lock file is provided. Thus this variable is not set.

Perhaps, equally importantly, on L376 it's defined using the result from `validate_sbom()`, which would only return a boolean. Based on the input to `get_spec_version()`, this should be either `spdx` or `cyclonedx`.

@kashifpk can you take a look here?
